const subjects = {
  Biology: ['Classification', 'Cells'], Mathematics: ['Number', 'Algebra'], 'Computer Science': ['Data', 'Networks'],
  Physics: ['Measurements', 'Motion'], Chemistry: ['Particles', 'Experiments'], 'Additional Maths': ['Functions', 'Quadratics'],
  Accounting: ['The accounting cycle', 'Double entry'], Economics: ['Basic economic problem', 'Demand and supply'],
  'Business Studies': ['Business activity', 'People in business'], English: ['Reading skills', 'Writing skills']
};
const state = JSON.parse(localStorage.getItem('studymonkey') || '{"subjects":["Biology"],"trial":3,"scores":[],"mode":"dark"}');
let screen = 'dashboard';
const app = document.querySelector('#app');
const save = () => localStorage.setItem('studymonkey', JSON.stringify(state));
const lessonText = 'Living things grow, use energy, respond to changes and reproduce. The tutor breaks difficult ideas into small steps so you can learn at your own pace.';
function shell(content) { return `<div class="shell"><aside class="sidebar"><h2 class="brand">✦ StudyMonkey</h2><div class="subject-label">IGCSE STUDY TUTOR</div><nav class="nav">${[['dashboard','Dashboard'],['learn','Learn chapters'],['tutor','Ask the tutor'],['quiz','Quick quiz'],['progress','My progress'],['settings','Settings']].map(([id,label]) => `<button class="${screen===id?'active':''}" onclick="go('${id}')">${label}</button>`).join('')}</nav><div class="profile">Amina<br><span>${state.trial} free classes left</span></div></aside><section class="content">${content}</section></div>`; }
function dashboard() { const options = state.subjects.map(s=>`<option>${s}</option>`).join(''); return shell(`<div class="toolbar"><div><div class="eyebrow">WELCOME BACK</div><h1>What will you learn today?</h1><p>Pick a chapter, ask for help, then test what you know.</p></div><select onchange="state.current=this.value;save();render()">${options}</select></div><div class="hero"><b>Continue learning</b><p>${state.current || state.subjects[0]} · Chapter 1: ${subjects[state.current || state.subjects[0]][0]}</p><button class="primary" onclick="go('learn')">Resume lesson</button></div><div class="cards">${state.subjects.map(subject => `<article class="card"><h3>${subject}</h3><p>Start with your first two chapters.</p><ul><li>Chapter 1: ${subjects[subject][0]}</li><li>Chapter 2: ${subjects[subject][1]}</li></ul><button onclick="state.current='${subject}';save();go('learn')">Open subject</button></article>`).join('')}</div>`); }
function learn() { const subject=state.current||state.subjects[0], chapter=subjects[subject][0]; return shell(`<div class="eyebrow">${subject.toUpperCase()} · CHAPTER 1</div><h1>${chapter}</h1><p>Short original lessons, made for your level.</p><article class="lesson"><h2>Simple explanation</h2><p>${lessonText}</p><div class="terms"><div class="term"><b>Key term</b><p>Organism: a living thing.</p></div><div class="term"><b>Example</b><p>A seed can grow into a plant.</p></div></div><div class="actions"><button onclick="go('tutor')">Ask about this lesson</button> <button class="primary" onclick="consumeTrial('quiz')">Try a quiz</button></div></article>`); }
function tutor() { return shell(`<div class="eyebrow">AI TUTOR</div><h1>Ask any doubt</h1><p>Try “Explain this more simply” or ask for an example.</p><div class="chat" id="chat"><div class="message">Hi! What are you finding difficult today?</div></div><div class="ask"><input id="question" placeholder="Ask anything you are unsure about..." /><button class="primary" onclick="askTutor()">Send</button></div>`); }
function quiz() { const subject=state.current||state.subjects[0]; return shell(`<div class="eyebrow">${subject.toUpperCase()} · QUICK QUIZ</div><h1>Check your understanding</h1><div class="quiz card"><h2>Which choice is best?</h2><p>After a lesson, what helps you remember the topic?</p><button class="answer" onclick="finishQuiz(false)">Reading the same sentence once</button><button class="answer" onclick="finishQuiz(true)">Explaining it in your own words and practising</button><button class="answer" onclick="finishQuiz(false)">Skipping all questions</button></div>`); }
function progress() { const last=state.scores.at(-1); return shell(`<div class="eyebrow">YOUR LEARNING</div><h1>My progress</h1><div class="cards"><article class="card"><h3>Free sessions</h3><p>${state.trial} of 3 still available.</p><button onclick="showPlans()">View plans</button></article><article class="card"><h3>Latest quiz</h3><p>${last ? `${last}/1 correct` : 'No quiz taken yet.'}</p></article><article class="card"><h3>Study next</h3><p>${state.current || state.subjects[0]} · Chapter 2</p><button class="primary" onclick="go('learn')">Continue</button></article></div>`); }
function settings() { return shell(`<div class="eyebrow">SETTINGS</div><h1>Your preferences and privacy</h1><div class="mode"><button class="${state.mode==='dark'?'primary':''}" onclick="setMode('dark')">Dark mode</button><button class="${state.mode==='eye'?'primary':''}" onclick="setMode('eye')">Eye-soothing mode</button></div><article class="card"><h2>Your privacy</h2><p>Your progress is stored only in this browser in this prototype. A real version will use private accounts, secure server storage, a clear privacy policy, and a delete-my-data option.</p><button onclick="if(confirm('Delete local StudyMonkey data?')){localStorage.removeItem('studymonkey');location.reload()}">Delete my local data</button></article><article class="card"><h2>Subjects</h2><p>Choose the subjects you want to keep on your dashboard.</p>${Object.keys(subjects).map(s=>`<label><input type="checkbox" ${state.subjects.includes(s)?'checked':''} onchange="toggleSubject('${s}',this.checked)"> ${s}</label><br>`).join('')}</article>`); }
function render() { document.documentElement.className=state.mode==='eye'?'eye':''; app.innerHTML = ({dashboard,learn,tutor,quiz,progress,settings}[screen])(); }
function go(next) { screen=next; render(); }
function setMode(mode) { state.mode=mode;save();render(); }
function toggleSubject(subject, checked) { state.subjects=checked?[...new Set([...state.subjects,subject])]:state.subjects.filter(s=>s!==subject); if(!state.subjects.length) state.subjects=['Biology'];save();render(); }
function askTutor() { const input=document.querySelector('#question'), question=input.value.trim(); if(!question)return; const chat=document.querySelector('#chat');chat.innerHTML+=`<div class="message user">${question}</div><div class="message">Let’s make that simple: ${lessonText} Try telling me which word is confusing and I will explain it another way.</div>`;input.value=''; }
function consumeTrial(next) { if(state.trial<=0){showPlans();return;} state.trial--;save();go(next); }
function finishQuiz(correct) { state.scores.push(correct?1:0);save(); app.innerHTML=shell(`<div class="results"><div class="eyebrow">QUIZ COMPLETE</div><h1>${correct?'Nice work!':'Good try!'}</h1><p>${correct?'You used a strong study method.':'The best answer is explaining in your own words and practising.'}</p><div class="notice">Next step: ${correct?'Continue to Chapter 2.':'Ask the tutor for another example, then retry.'}</div><p><button class="primary" onclick="go('learn')">Continue learning</button> <button onclick="go('tutor')">Ask the tutor</button></p></div>`); }
function showPlans() { document.querySelector('#plans').classList.remove('hidden'); }
function closePlans() { document.querySelector('#plans').classList.add('hidden'); }
document.body.insertAdjacentHTML('beforeend', `<div id="plans" class="modal hidden"><div class="modal-box"><button onclick="closePlans()">Close</button><h2>Choose your study plan</h2><p>Start with 3 free AI lesson sessions. Prices are placeholders until you decide your currency.</p><div class="plans"><div class="plan"><h3>Free trial</h3><p>3 AI lesson sessions, tutor explanations, mini quizzes.</p></div><div class="plan featured"><h3>Study Plus</h3><p>Unlimited tutor questions, lessons, quizzes, progress, and audio.</p><button class="primary">Choose Plus</button></div><div class="plan"><h3>Exam Pro</h3><p>Everything in Plus, revision plans, exam practice, and reminders.</p><button>Choose Pro</button></div></div></div></div>`);
render();

