import { initAuth } from './auth.js?v=firebase-3';
import { curriculum, getLesson } from './curriculum.js?v=curriculum-1';
import { TUTOR_API_URL } from './config.js?v=tutor-1';
let enhanceExperience = () => {};
import('./experience.js?v=game-3').then(module => { enhanceExperience = module.enhanceExperience; enhanceExperience(screen); }).catch(() => {});

const releaseVersion = 'v1.2.0';
const subjects = curriculum;
const firstLessons = {
  Biology: { explanation: 'Living things grow, use energy, respond to changes and reproduce. We learn science best by breaking one big idea into small steps.', term: 'Organism: a living thing.', example: 'A seed can grow into a plant.' },
  Mathematics: { explanation: 'Numbers are useful because they help us compare, measure, and solve problems. Start by identifying what the question gives you and what it asks for.', term: 'Integer: a whole number, including negative numbers and zero.', example: 'In −3 + 5, the answer is 2.' },
  'Computer Science': { explanation: 'Data is information that a computer can store and process. Computers use clear instructions to turn data into useful results.', term: 'Data: facts or values that can be stored and processed.', example: 'A student name and test score are pieces of data.' },
  Physics: { explanation: 'Physics explains how the world works using careful measurements and tests. Measuring accurately helps us make fair comparisons.', term: 'Measurement: finding the size or amount of something using a unit.', example: 'The length of a desk can be measured in centimetres.' },
  Chemistry: { explanation: 'Chemistry studies substances, what they are made from, and how they change. Tiny particles explain many things we can see.', term: 'Particle: a very small piece of matter.', example: 'Ice, water, and steam are made from the same particles arranged differently.' },
  'Additional Maths': { explanation: 'Additional Maths builds stronger problem-solving skills. A function connects each allowed input to one output.', term: 'Function: a rule that gives one output for each input.', example: 'For y = 2x, if x is 3, y is 6.' },
  Accounting: { explanation: 'Accounting helps a business record money clearly. Every transaction affects at least two parts of the records.', term: 'Transaction: an exchange involving money or value.', example: 'Buying equipment with cash changes both equipment and cash.' },
  Economics: { explanation: 'Economics looks at choices because people and countries do not have unlimited resources. Every choice has a cost.', term: 'Scarcity: having limited resources but many wants.', example: 'Choosing to revise one subject means giving up time for another activity.' },
  'Business Studies': { explanation: 'Business Studies explains how organisations meet customer needs while managing people, money, and resources.', term: 'Business: an organisation that provides goods or services.', example: 'A bakery provides bread and other food to customers.' },
  English: { explanation: 'Strong reading starts by finding what a writer says, then thinking about how and why they say it. Use evidence from the text.', term: 'Inference: an idea you work out from clues in a text.', example: 'A character shivering may suggest that they are cold or frightened.' }
};
const quizQuestions = {
  Biology: ['What is an organism?', ['A living thing', 'A type of rock', 'A measuring tool'], 0],
  Mathematics: ['What is −3 + 5?', ['−8', '2', '8'], 1],
  'Computer Science': ['Which is an example of data?', ['A student test score', 'A computer screen', 'A keyboard cable'], 0],
  Physics: ['Which unit is useful for measuring the length of a desk?', ['Centimetres', 'Litres', 'Seconds'], 0],
  Chemistry: ['What is matter made of?', ['Particles', 'Only light', 'Only energy'], 0],
  'Additional Maths': ['For y = 2x, what is y when x = 3?', ['5', '6', '9'], 1],
  Accounting: ['What is a transaction?', ['An exchange involving money or value', 'A type of business building', 'A spelling mistake'], 0],
  Economics: ['What does scarcity mean?', ['Unlimited resources', 'Limited resources and many wants', 'No choices to make'], 1],
  'Business Studies': ['What does a business provide?', ['Goods or services', 'Only exams', 'Only homework'], 0],
  English: ['What is an inference?', ['Repeating a sentence', 'An idea worked out from clues', 'A punctuation mark'], 1]
};
let state = { subjects: ['Biology'], trial: 3, scores: [], mode: 'dark' };
state = await initAuth(state);
let screen = state.onboarded ? 'dashboard' : 'onboarding';
const app = document.querySelector('#app');
const save = () => window.studymonkeyAuth?.syncState(state);
function shell(content) { const verificationNotice = window.studymonkeyAuth?.email && !window.studymonkeyAuth?.emailVerified ? `<div class="notice"><b>Verify your email:</b> ${window.studymonkeyAuth.signInNotice || 'Check your inbox to verify your StudyMonkey account.'} <button class="text-button" onclick="resendVerification()">Resend email</button></div>` : ''; const storageNotice = window.studymonkeyAuth?.email && !window.studymonkeyAuth?.storageReady ? '<div class="notice">Your account works, but Firebase could not save your latest progress. Refresh and try again.</div>' : ''; const accountButton = window.studymonkeyAuth?.email ? `<button class="text-button" onclick="signOut()">${window.studymonkeyAuth?.isDemo?'Exit demo':'Sign out'}</button>` : ''; const items=[['dashboard','⌁','Command centre'],['learn','◈','Mission map'],['lab','◎','3D visual lab'],['tutor','✦','AI tutor'],['quiz','◇','Challenge arena'],['progress','↗','Player stats'],['settings','⚙','Settings']]; return `<div class="shell"><aside class="sidebar"><div><h2 class="brand"><span>SM</span> StudyMonkey</h2><div class="subject-label">IGCSE LEARNING OS · ${releaseVersion}</div></div><nav class="nav">${items.map(([id,icon,label]) => `<button class="${screen===id?'active':''}" onclick="go('${id}')"><i>${icon}</i>${label}</button>`).join('')}</nav><div class="profile"><span class="profile-dot"></span><div>${window.studymonkeyAuth?.email || 'StudyMonkey student'}<br><small>${window.studymonkeyAuth?.isDemo?'Demo explorer':'Free player'}</small></div>${accountButton}</div></aside><section class="content">${verificationNotice}${storageNotice}${content}</section></div>`; }
function onboarding() { return `<main class="onboarding"><section class="onboarding-card"><div class="eyebrow">WELCOME TO STUDYMONKEY</div><h1>Choose your IGCSE subjects</h1><p>Pick every subject you study. You can change these later in Settings.</p><div class="subject-picker">${Object.keys(subjects).map(subject => `<label><input type="checkbox" value="${subject}" ${state.subjects.includes(subject) ? 'checked' : ''}> ${subject}</label>`).join('')}</div><p id="onboarding-message" role="status"></p><button class="primary" onclick="finishOnboarding()">Start studying</button></section></main>`; }
function dashboard() { const subject=state.current||state.subjects[0], chapterIndex=state.currentChapter||0, lesson=getLesson(subject,chapterIndex), xp=state.scores.reduce((total,score)=>total+(score?120:35),0), mastery=Math.min(100,Math.round((state.scores.length/Math.max(1,subjects[subject].length))*100)), options=state.subjects.map(item=>`<option value="${item}" ${item===subject?'selected':''}>${item}</option>`).join(''); return shell(`<section class="command-bar"><div><p class="mission-kicker">TODAY'S MISSION</p><h1>Enter the ${subject} zone.</h1><p>One focused mission. One clear win. Keep moving through the syllabus.</p></div><select aria-label="Current subject" onchange="changeSubject(this.value)">${options}</select></section><section class="mission-deck"><div class="mission-copy"><span class="status-chip">MISSION ${chapterIndex+1} OF ${subjects[subject].length}</span><h2>${lesson.chapter}</h2><p>${lesson.explanation}</p><div class="mission-actions"><button class="primary" onclick="go('learn')">Launch mission</button><button onclick="go('tutor')">Ask before starting</button></div></div><div class="cell-scan" aria-label="Animated cell scan"><div class="scan-line"></div><div class="cell-core"></div><span class="orb orb-a"></span><span class="orb orb-b"></span><span class="orb orb-c"></span><p>${subject==='Biology'?'CELL SCAN':'CONCEPT SCAN'}</p></div></section><section class="player-strip" aria-label="Learning progress"><div><span>XP</span><strong>${xp}</strong></div><div><span>Mastery</span><strong>${mastery}%</strong></div><div><span>Completed</span><strong>${state.scores.length}</strong></div><div class="mastery-track"><span style="width:${mastery}%"></span></div></section><section class="worlds"><div class="section-heading"><h2>Your subject worlds</h2><p>Choose a world and continue from any unit.</p></div><div class="world-grid">${state.subjects.map((item,index)=>`<button class="world-tile" onclick="openSubject('${item}')"><span class="world-index">${String(index+1).padStart(2,'0')}</span><strong>${item}</strong><small>${subjects[item].length} missions</small><i>Enter world</i></button>`).join('')}</div></section>`); }
function learn() { const subject = state.current || state.subjects[0], chapterIndex = state.currentChapter || 0, lesson = getLesson(subject, chapterIndex), biologyMission=subject==='Biology'&&chapterIndex===0?`<section class="cell-mission"><div class="cell-diagram" aria-label="Interactive animal cell"><button class="organelle nucleus" onclick="cellFocus('Nucleus','Controls the cell and contains genetic material.')">Nucleus</button><button class="organelle mitochondria" onclick="cellFocus('Mitochondria','Release energy through aerobic respiration.')">Mitochondria</button><button class="organelle ribosome" onclick="cellFocus('Ribosomes','Build proteins needed for growth and repair.')">Ribosomes</button></div><div class="cell-readout"><span>INTERACTIVE SCAN</span><h3 id="cell-part">Choose an organelle</h3><p id="cell-detail">Select a labelled part of the cell to reveal its job.</p></div></section>`:''; return shell(`<div class="toolbar"><div><p class="mission-kicker">${subject.toUpperCase()} · MISSION ${chapterIndex + 1}</p><h1>${lesson.chapter}</h1><p>Explore the idea, interact with it, then prove you understand it.</p></div><button onclick="go('lab')">Open 3D lab</button></div><div class="unit-grid">${subjects[subject].map((chapter, index) => `<button class="unit-button ${index === chapterIndex ? 'active' : ''}" onclick="openChapter(${index})"><span>Mission ${index + 1}</span>${chapter}</button>`).join('')}</div>${biologyMission}<article class="lesson"><h2>Mission briefing</h2><p id="lesson-explanation">${lesson.explanation}</p><div class="terms"><div class="term"><b>Key term</b><p>${lesson.term}</p></div><div class="term"><b>Field note</b><p>${lesson.example}</p></div></div><div id="summary"></div><div class="actions"><button onclick="showSummary()">Build recap</button><button onclick="readLesson()">Listen</button><button onclick="go('tutor')">Ask tutor</button> <button class="primary" onclick="consumeTrial('quiz')">Complete checkpoint</button></div></article>`); }
function lab() { const subject = state.current || state.subjects[0]; return shell(`<div class="toolbar"><div><p class="mission-kicker">IMMERSIVE CONCEPT ENGINE</p><h1>Interactive 3D study lab</h1><p>Drag to rotate, scroll to zoom, and use the selected subject to change the model.</p></div><select aria-label="3D lab subject" onchange="changeLabSubject(this.value)">${state.subjects.map(item => `<option value="${item}" ${item === subject ? 'selected' : ''}>${item}</option>`).join('')}</select></div><section class="lab-panel"><div id="study-model" class="study-model" aria-label="Interactive three-dimensional learning model"><div class="css-model" aria-hidden="true"><div class="model-orbit orbit-one"><i></i></div><div class="model-orbit orbit-two"><i></i></div><div class="model-shell"><span>${subject.slice(0,2).toUpperCase()}</span></div><b>${subject}</b></div></div><div class="lab-copy"><span class="status-chip">LIVE MODEL</span><h2>${subject} visual</h2><p id="lab-description">Explore the concept from every angle. The full WebGL model loads automatically when supported.</p><div class="lab-keys"><span>DRAG <b>rotate</b></span><span>SCROLL <b>zoom</b></span></div><button onclick="go('learn')">Back to missions</button></div></section>`); }
function tutor() { const subject=state.current||state.subjects[0], lesson=getLesson(subject,state.currentChapter||0); return shell(`<div class="eyebrow">AI TUTOR</div><h1>Ask any doubt</h1><p>Ask anything about ${subject}: ${lesson.chapter}.</p><div class="chat" id="chat" aria-live="polite"><div class="message">I know you are studying <b>${subject}</b>, unit <b>${lesson.chapter}</b>. What do you want help with?</div></div><div class="ask"><input id="question" placeholder="Ask anything you are unsure about..." onkeydown="if(event.key==='Enter') askTutor()" /><button class="primary" id="ask-button" onclick="askTutor()">Send</button></div>`); }
function quiz() { const subject=state.current||state.subjects[0], [question, answers, correctAnswer] = quizQuestions[subject]; return shell(`<div class="eyebrow">${subject.toUpperCase()} · QUICK QUIZ</div><h1>Check your understanding</h1><div class="quiz card"><h2>One question at a time</h2><p>${question}</p>${answers.map((answer, index) => `<button class="answer" onclick="finishQuiz(${index === correctAnswer})">${answer}</button>`).join('')}</div>`); }
function progress() { const last=state.scores.at(-1); return shell(`<div class="eyebrow">YOUR LEARNING</div><h1>My progress</h1><div class="cards"><article class="card"><h3>Free access</h3><p>Lessons, quizzes, audio, and progress tracking are unlocked during the MVP launch.</p><button onclick="showPlans()">Future Plus features</button></article><article class="card"><h3>Latest quiz</h3><p>${last !== undefined ? `${last}/1 correct` : 'No quiz taken yet.'}</p></article><article class="card"><h3>Study next</h3><p>${state.current || state.subjects[0]} · Chapter 2</p><button class="primary" onclick="go('learn')">Continue</button></article></div>`); }
function settings() { const verified = window.studymonkeyAuth?.emailVerified; return shell(`<div class="eyebrow">SETTINGS</div><h1>Your preferences and privacy</h1><div class="mode"><button class="${state.mode==='dark'?'primary':''}" onclick="setMode('dark')">Dark mode</button><button class="${state.mode==='eye'?'primary':''}" onclick="setMode('eye')">Eye-soothing mode</button></div><article class="card"><h2>Your account</h2><p>Your subjects, quiz results, trial use, and display preferences are saved privately in Firebase.</p><p>Email status: <b>${verified ? 'Verified' : 'Not verified yet'}</b></p>${verified ? '' : '<button onclick="resendVerification()">Resend verification email</button>'}</article><article class="card"><h2>Subjects</h2><p>Choose the subjects you want to keep on your dashboard.</p>${Object.keys(subjects).map(s=>`<label><input type="checkbox" ${state.subjects.includes(s)?'checked':''} onchange="toggleSubject('${s}',this.checked)"> ${s}</label><br>`).join('')}</article>`); }
function render() { document.documentElement.className=state.mode==='eye'?'eye':''; app.innerHTML = ({ onboarding, dashboard, learn, lab, tutor, quiz, progress, settings }[screen])(); enhanceExperience(screen); if (screen === 'lab') mountLab(); }
function go(next) { screen=next; render(); }
function setMode(mode) { state.mode=mode;save();render(); }
function changeSubject(subject) { state.current = subject; save(); render(); }
function openSubject(subject) { state.current = subject; state.currentChapter = 0; save(); go('learn'); }
function openChapter(chapterIndex) { state.currentChapter = chapterIndex; save(); render(); }
function changeLabSubject(subject) { state.current = subject; state.currentChapter = 0; save(); render(); }
async function mountLab() { const subject = state.current || state.subjects[0], container = document.querySelector('#study-model'), description = document.querySelector('#lab-description'); try { const { mountStudyModel } = await import('./visual-lab.js?v=lab-2'); mountStudyModel(container, subject, description); } catch (error) { description.textContent = 'The 3D model could not load right now. Your study units are still available.'; } }
function signOut() { window.studymonkeyAuth?.signOut(); }
async function resendVerification() { const message = await window.studymonkeyAuth?.resendVerification(); alert(message || 'Could not send the verification email.'); }
function finishOnboarding() { const chosen = [...document.querySelectorAll('.subject-picker input:checked')].map(input => input.value); if (!chosen.length) { document.querySelector('#onboarding-message').textContent = 'Choose at least one subject to begin.'; return; } state.subjects = chosen; state.current = chosen[0]; state.onboarded = true; save(); go('dashboard'); }
function showSummary() { const lesson = getLesson(state.current || state.subjects[0], state.currentChapter || 0); document.querySelector('#summary').innerHTML = `<div class="notice"><b>Short summary:</b> ${lesson.explanation} Remember: ${lesson.term}</div>`; }
function readLesson() { const lesson = getLesson(state.current || state.subjects[0], state.currentChapter || 0); if (!('speechSynthesis' in window)) { alert('Read aloud is not supported by this browser.'); return; } window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(`${lesson.explanation} ${lesson.term} ${lesson.example}`)); }
function cellFocus(name, detail) { const part=document.querySelector('#cell-part'), copy=document.querySelector('#cell-detail'); if(part)part.textContent=name;if(copy)copy.textContent=detail; }
function toggleSubject(subject, checked) { state.subjects=checked?[...new Set([...state.subjects,subject])]:state.subjects.filter(s=>s!==subject); if(!state.subjects.length) state.subjects=['Biology'];save();render(); }
async function askTutor() { const input=document.querySelector('#question'), question=input.value.trim(), chat=document.querySelector('#chat'), button=document.querySelector('#ask-button'); if(!question||!chat)return; const userMessage=document.createElement('div'), tutorMessage=document.createElement('div'), controller=new AbortController(), timeout=setTimeout(()=>controller.abort(),45000); userMessage.className='message user'; userMessage.textContent=question; tutorMessage.className='message'; tutorMessage.textContent='Thinking...'; chat.append(userMessage,tutorMessage); input.value=''; button.disabled=true; try { if(!TUTOR_API_URL) throw new Error('The real tutor server is not connected yet.'); const token=await window.studymonkeyAuth?.getIdToken(); if(!token) throw new Error('Please sign in again before asking the tutor.'); const lesson=getLesson(state.current||state.subjects[0],state.currentChapter||0); const response=await fetch(TUTOR_API_URL,{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({question,subject:state.current||state.subjects[0],unit:lesson.chapter})}); const data=await response.json(); if(!response.ok) throw new Error(data.error||'The tutor could not answer right now.'); tutorMessage.textContent=data.answer; } catch(error) { tutorMessage.textContent=error.name==='AbortError'?'The tutor took too long to answer. Please try again.':error.message||'The tutor could not answer right now.'; } finally { clearTimeout(timeout); button.disabled=false; chat.scrollTop=chat.scrollHeight; } }
function consumeTrial(next) { go(next); }
function finishQuiz(correct) { const subject=state.current||state.subjects[0], correctAnswer=quizQuestions[subject][1][quizQuestions[subject][2]]; state.scores.push(correct?1:0);save(); app.innerHTML=shell(`<div class="results"><div class="eyebrow">QUIZ COMPLETE</div><h1>${correct?'Nice work!':'Good try!'}</h1><p>${correct?'That answer is correct.':`The correct answer is: ${correctAnswer}.`}</p><div class="notice">Next step: ${correct?'Continue to Chapter 2.':'Ask the tutor for another example, then retry.'}</div><p><button class="primary" onclick="go('learn')">Continue learning</button> <button onclick="go('tutor')">Ask the tutor</button></p></div>`); }
function showPlans() { document.querySelector('#plans').classList.remove('hidden'); }
function closePlans() { document.querySelector('#plans').classList.add('hidden'); }
function selectPlan() { document.querySelector('#plan-message').textContent = 'StudyMonkey is free while we build it. StudyMonkey Plus will be available later with extra exam practice and personalised revision plans.'; }
document.body.insertAdjacentHTML('beforeend', `<div id="plans" class="modal hidden"><div class="modal-box"><button onclick="closePlans()">Close</button><h2>StudyMonkey is free for now</h2><p>Use the tutor, lessons, quizzes, audio, and progress tracker without payment while the app is being built.</p><div class="plans"><div class="plan featured"><h3>StudyMonkey Plus</h3><p>One optional future subscription with extra exam practice, personalised revision plans, and priority new features.</p><button class="primary" onclick="selectPlan()">Tell me about Plus</button></div></div><p id="plan-message" role="status"></p></div></div>`);
Object.assign(window, { askTutor, cellFocus, changeLabSubject, changeSubject, closePlans, consumeTrial, finishOnboarding, finishQuiz, go, openChapter, openSubject, readLesson, resendVerification, selectPlan, setMode, showPlans, showSummary, signOut, toggleSubject });
render();

