import { initAuth } from './auth.js';

const subjects = {
  Biology: ['Classification', 'Cells'], Mathematics: ['Number', 'Algebra'], 'Computer Science': ['Data', 'Networks'],
  Physics: ['Measurements', 'Motion'], Chemistry: ['Particles', 'Experiments'], 'Additional Maths': ['Functions', 'Quadratics'],
  Accounting: ['The accounting cycle', 'Double entry'], Economics: ['Basic economic problem', 'Demand and supply'],
  'Business Studies': ['Business activity', 'People in business'], English: ['Reading skills', 'Writing skills']
};
const firstLessons = {
  Biology: { explanation: 'Living things grow, use energy, respond to changes and reproduce. We learn science best by breaking one big idea into small steps.', term: 'Organism: a living thing.', example: 'A seed can grow into a plant.' },
  Mathematics: { explanation: 'Numbers are useful because they help us compare, measure, and solve problems. Start by identifying what the question gives you and what it asks for.', term: 'Integer: a whole number, including negative numbers and zero.', example: 'In −3 + 5, the answer is 2.' },
  'Computer Science': { explanation: 'Data is information that a computer can store and process. Computers use clear instructions to turn data into useful results.', term: 'Data: facts or values that can be stored and processed.', example: 'A student name and test score are pieces of data.' },
  Physics: { explanation: 'Physics explains how the world works using careful measurements and tests. Measuring accurately helps us make fair comparisons.', term: 'Measurement: finding the size or amount of something using a unit.', example: 'The length of a desk can be measured in centimetres.' },
  Chemistry: { explanation: 'Chemistry studies substances, what they are made from, and how they change. Tiny particles explain many things we can see.', term: 'Particle: a very small piece of matter.', example: 'Ice, water, and steam are made from the same particles arranged differently.' },
  'Additional Maths': { explanation: 'Additional Maths builds stronger problem-solving skills. A function connects each allowed input to one output.', term: 'Function: a rule that gives one output for each input.', example: 'For y = 2x, if x is 3, y is 6.' },
  Accounting: { explanation: 'Accounting helps a business record money clearly. Every transaction affects at least two parts of the records.', term: 'Transaction: an exchange involving money or value.', example: 'Buying equipment with cash changes both equipment and cash.' },
  Economics: { explanation: 'Economics looks at choices because people and countries do not have unlimited resources. Every choice has a cost.', term: 'Scarcity: having limited resources but many wants.', example: 'Choosing to revise one subject means giving up time for another activity.' },
  'Business Studies': { explanation: 'Business Studies explains how organisations meet customer needs while managing people, money, and resources.', term: 'Business: an organisation that provides goods or services.', example: 'A bakery provides bread and other food to customers.' },
  English: { explanation: 'Strong reading starts by finding what a writer says, then thinking about how and why they say it. Use evidence from the text.', term: 'Inference: an idea you work out from clues in a text.', example: 'A character shivering may suggest that they are cold or frightened.' }
};
const quizQuestions = {
  Biology: ['What is an organism?', ['A living thing', 'A type of rock', 'A measuring tool'], 0],
  Mathematics: ['What is −3 + 5?', ['−8', '2', '8'], 1],
  'Computer Science': ['Which is an example of data?', ['A student test score', 'A computer screen', 'A keyboard cable'], 0],
  Physics: ['Which unit is useful for measuring the length of a desk?', ['Centimetres', 'Litres', 'Seconds'], 0],
  Chemistry: ['What is matter made of?', ['Particles', 'Only light', 'Only energy'], 0],
  'Additional Maths': ['For y = 2x, what is y when x = 3?', ['5', '6', '9'], 1],
  Accounting: ['What is a transaction?', ['An exchange involving money or value', 'A type of business building', 'A spelling mistake'], 0],
  Economics: ['What does scarcity mean?', ['Unlimited resources', 'Limited resources and many wants', 'No choices to make'], 1],
  'Business Studies': ['What does a business provide?', ['Goods or services', 'Only exams', 'Only homework'], 0],
  English: ['What is an inference?', ['Repeating a sentence', 'An idea worked out from clues', 'A punctuation mark'], 1]
};
let state = JSON.parse(localStorage.getItem('studymonkey') || '{"subjects":["Biology"],"trial":3,"scores":[],"mode":"dark"}');
state = await initAuth(state);
let screen = state.onboarded ? 'dashboard' : 'onboarding';
const app = document.querySelector('#app');
const save = () => {
  localStorage.setItem('studymonkey', JSON.stringify(state));
  window.studymonkeyAuth?.syncState(state);
};
function shell(content) { const notice = window.studymonkeyAuth?.isConfigured ? '' : '<div class="notice">Account setup is ready. Add your Supabase project details in <code>config.js</code> to enable real student sign-in.</div>'; const accountButton = window.studymonkeyAuth?.email ? '<button class="text-button" onclick="signOut()">Sign out</button>' : ''; return `<div class="shell"><aside class="sidebar"><h2 class="brand">✦ StudyMonkey</h2><div class="subject-label">IGCSE STUDY TUTOR</div><nav class="nav">${[['dashboard','Dashboard'],['learn','Learn chapters'],['tutor','Ask the tutor'],['quiz','Quick quiz'],['progress','My progress'],['settings','Settings']].map(([id,label]) => `<button class="${screen===id?'active':''}" onclick="go('${id}')">${label}</button>`).join('')}</nav><div class="profile">${window.studymonkeyAuth?.email || 'StudyMonkey student'}<br><span>${state.trial} free classes left</span><br>${accountButton}</div></aside><section class="content">${notice}${content}</section></div>`; }
function onboarding() { return `<main class="onboarding"><section class="onboarding-card"><div class="eyebrow">WELCOME TO STUDYMONKEY</div><h1>Choose your IGCSE subjects</h1><p>Pick every subject you study. You can change these later in Settings.</p><div class="subject-picker">${Object.keys(subjects).map(subject => `<label><input type="checkbox" value="${subject}" ${state.subjects.includes(subject) ? 'checked' : ''}> ${subject}</label>`).join('')}</div><p id="onboarding-message" role="status"></p><button class="primary" onclick="finishOnboarding()">Start studying</button></section></main>`; }
function dashboard() { const options = state.subjects.map(s=>`<option>${s}</option>`).join(''); return shell(`<div class="toolbar"><div><div class="eyebrow">WELCOME BACK</div><h1>What will you learn today?</h1><p>Pick a chapter, ask for help, then test what you know.</p></div><select onchange="state.current=this.value;save();render()">${options}</select></div><div class="hero"><b>Continue learning</b><p>${state.current || state.subjects[0]} · Chapter 1: ${subjects[state.current || state.subjects[0]][0]}</p><button class="primary" onclick="go('learn')">Resume lesson</button></div><div class="cards">${state.subjects.map(subject => `<article class="card"><h3>${subject}</h3><p>Start with your first two chapters.</p><ul><li>Chapter 1: ${subjects[subject][0]}</li><li>Chapter 2: ${subjects[subject][1]}</li></ul><button onclick="state.current='${subject}';save();go('learn')">Open subject</button></article>`).join('')}</div>`); }
function learn() { const subject=state.current||state.subjects[0], chapter=subjects[subject][0], lesson=firstLessons[subject]; return shell(`<div class="eyebrow">${subject.toUpperCase()} · CHAPTER 1</div><h1>${chapter}</h1><p>Short original lessons, made for your level.</p><article class="lesson"><h2>Simple explanation</h2><p id="lesson-explanation">${lesson.explanation}</p><div class="terms"><div class="term"><b>Key term</b><p>${lesson.term}</p></div><div class="term"><b>Example</b><p>${lesson.example}</p></div></div><div id="summary"></div><div class="actions"><button onclick="showSummary()">Make a summary</button><button onclick="readLesson()">Read aloud</button><button onclick="go('tutor')">Ask about this lesson</button> <button class="primary" onclick="consumeTrial('quiz')">Try a quiz</button></div></article>`); }
function tutor() { return shell(`<div class="eyebrow">AI TUTOR</div><h1>Ask any doubt</h1><p>Try “Explain this more simply” or ask for an example.</p><div class="chat" id="chat"><div class="message">Hi! What are you finding difficult today?</div></div><div class="ask"><input id="question" placeholder="Ask anything you are unsure about..." /><button class="primary" onclick="askTutor()">Send</button></div>`); }
function quiz() { const subject=state.current||state.subjects[0], [question, answers, correctAnswer] = quizQuestions[subject]; return shell(`<div class="eyebrow">${subject.toUpperCase()} · QUICK QUIZ</div><h1>Check your understanding</h1><div class="quiz card"><h2>One question at a time</h2><p>${question}</p>${answers.map((answer, index) => `<button class="answer" onclick="finishQuiz(${index === correctAnswer})">${answer}</button>`).join('')}</div>`); }
function progress() { const last=state.scores.at(-1); return shell(`<div class="eyebrow">YOUR LEARNING</div><h1>My progress</h1><div class="cards"><article class="card"><h3>Free sessions</h3><p>${state.trial} of 3 still available.</p><button onclick="showPlans()">View plans</button></article><article class="card"><h3>Latest quiz</h3><p>${last ? `${last}/1 correct` : 'No quiz taken yet.'}</p></article><article class="card"><h3>Study next</h3><p>${state.current || state.subjects[0]} · Chapter 2</p><button class="primary" onclick="go('learn')">Continue</button></article></div>`); }
function settings() { const accountMessage = window.studymonkeyAuth?.email ? 'Your selected subjects, quiz results, and display preferences are stored in your private account.' : 'Your progress is stored only in this browser until you connect a private account.'; return shell(`<div class="eyebrow">SETTINGS</div><h1>Your preferences and privacy</h1><div class="mode"><button class="${state.mode==='dark'?'primary':''}" onclick="setMode('dark')">Dark mode</button><button class="${state.mode==='eye'?'primary':''}" onclick="setMode('eye')">Eye-soothing mode</button></div><article class="card"><h2>Your privacy</h2><p>${accountMessage}</p><p>Deleting browser data removes this device’s saved copy. It does not delete your online account.</p><button onclick="if(confirm('Delete local StudyMonkey data?')){localStorage.removeItem('studymonkey');location.reload()}">Delete browser data</button></article><article class="card"><h2>Subjects</h2><p>Choose the subjects you want to keep on your dashboard.</p>${Object.keys(subjects).map(s=>`<label><input type="checkbox" ${state.subjects.includes(s)?'checked':''} onchange="toggleSubject('${s}',this.checked)"> ${s}</label><br>`).join('')}</article>`); }
function render() { document.documentElement.className=state.mode==='eye'?'eye':''; app.innerHTML = ({ onboarding, dashboard, learn, tutor, quiz, progress, settings }[screen])(); }
function go(next) { screen=next; render(); }
function setMode(mode) { state.mode=mode;save();render(); }
function signOut() { window.studymonkeyAuth?.signOut(); }
function finishOnboarding() { const chosen = [...document.querySelectorAll('.subject-picker input:checked')].map(input => input.value); if (!chosen.length) { document.querySelector('#onboarding-message').textContent = 'Choose at least one subject to begin.'; return; } state.subjects = chosen; state.current = chosen[0]; state.onboarded = true; save(); go('dashboard'); }
function showSummary() { const subject = state.current || state.subjects[0], lesson = firstLessons[subject]; document.querySelector('#summary').innerHTML = `<div class="notice"><b>Short summary:</b> ${lesson.explanation} Remember: ${lesson.term}</div>`; }
function readLesson() { const subject = state.current || state.subjects[0], lesson = firstLessons[subject]; if (!('speechSynthesis' in window)) { alert('Read aloud is not supported by this browser.'); return; } window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(`${lesson.explanation} ${lesson.term} ${lesson.example}`)); }
function toggleSubject(subject, checked) { state.subjects=checked?[...new Set([...state.subjects,subject])]:state.subjects.filter(s=>s!==subject); if(!state.subjects.length) state.subjects=['Biology'];save();render(); }
function askTutor() { const input=document.querySelector('#question'), question=input.value.trim(); if(!question)return; const chat=document.querySelector('#chat'), lesson=firstLessons[state.current||state.subjects[0]];chat.innerHTML+=`<div class="message user">${question}</div><div class="message">Let’s make that simple: ${lesson.explanation} Key term: ${lesson.term} Tell me which word is confusing and I will explain it another way.</div>`;input.value=''; }
function consumeTrial(next) { if(state.trial<=0){showPlans();return;} state.trial--;save();go(next); }
function finishQuiz(correct) { state.scores.push(correct?1:0);save(); app.innerHTML=shell(`<div class="results"><div class="eyebrow">QUIZ COMPLETE</div><h1>${correct?'Nice work!':'Good try!'}</h1><p>${correct?'You used a strong study method.':'The best answer is explaining in your own words and practising.'}</p><div class="notice">Next step: ${correct?'Continue to Chapter 2.':'Ask the tutor for another example, then retry.'}</div><p><button class="primary" onclick="go('learn')">Continue learning</button> <button onclick="go('tutor')">Ask the tutor</button></p></div>`); }
function showPlans() { document.querySelector('#plans').classList.remove('hidden'); }
function closePlans() { document.querySelector('#plans').classList.add('hidden'); }
function selectPlan(plan) { document.querySelector('#plan-message').textContent = `${plan} is planned, but payments are not live yet. No money has been taken.`; }
document.body.insertAdjacentHTML('beforeend', `<div id="plans" class="modal hidden"><div class="modal-box"><button onclick="closePlans()">Close</button><h2>Choose your study plan</h2><p>Start with 3 free AI lesson sessions. Plans below are a preview only until payments are connected.</p><div class="plans"><div class="plan"><h3>Free trial</h3><p>3 AI lesson sessions, tutor explanations, mini quizzes.</p></div><div class="plan featured"><h3>Study Plus</h3><p>Unlimited tutor questions, lessons, quizzes, progress, and audio.</p><button class="primary" onclick="selectPlan('Study Plus')">I’m interested</button></div><div class="plan"><h3>Exam Pro</h3><p>Everything in Plus, revision plans, exam practice, and reminders.</p><button onclick="selectPlan('Exam Pro')">I’m interested</button></div></div><p id="plan-message" role="status"></p></div></div>`);
Object.assign(window, { askTutor, closePlans, consumeTrial, finishOnboarding, finishQuiz, go, readLesson, selectPlan, setMode, showPlans, showSummary, signOut, toggleSubject });
render();
